version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    rebase-strategy: auto
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
